### ISSUE TITLE
libssh2 dylibs for MacOS

### ISSUE THREAD

**Issue by vdhub** [charonn0/RB-libssh2#4]
I guess is more a feature than a bug, I tried to run the project on xojo 2020r2 on Catalina and it keep on crashing on me, based on the example here https://github.com/charonn0/RB-libssh2/wiki/Process-Start-Example it gives me an error on "sh.Poll()" that I must use the value returned by that and then if I comment this and ignore it I get the second error that it does not find the dylibs. 

Is there a way to have all this without any plugins and have it run normally on a Mac? 

Thanks in advance.

**Comment by charonn0** [comment]
The process start example was wrong (I've corrected it.) `Poll()` returns True/False so its return value must be explicitly handled, either by storing it in a variable or by using the `Call` keyword to discard it. 

>I get the second error that it does not find the dylibs

It's expecting to find the libssh2 dylib at `@executable_path/../Frameworks/libssh2.1.dylib`, and the libcrypto dylib at `@executable_path/../Frameworks/libcrypto.1.1.dylib`. I don't use mac so I'm kind of fuzzy on the details of getting it working on that OS, but I think you need to have the IDE [copy the files as a build step](https://docs.xojo.com/UserGuide:Build_Automation#Copy_Files).

**Comment by vdhub** [comment]
Well I guess I added those but it seems that in case I put it in the window in a button action it locks the whole window and makes it unresponsive. So far seeing in the debug it does connect to the ssh but so far I see no response from it . 

I did tried as well 

`Dim sh As SSH.Channel = SSH.OpenChannel("ssh://user:password@public.example.com/")
  Call sh.Execute("uptime")
  Dim result As String
  Do Until sh.EOF
    If sh.PollReadable() Then
      result = result + sh.Read(sh.BytesReadable, 0)
    End If
  Loop
  sh.Close`

But no luck here as well. 

Did you tried having this in a worker I guess ? I assume that it will work way better there than in the main window. 

I guess a real xojo working example will help a lot . 

Thanks.

**Comment by charonn0** [comment]
I haven't tried it in a worker (don't have a high enough license level), but from what I've seen and heard they are an **ideal** way to use libssh2 from Xojo. It's almost as if they were designed specifically for this project.

The second-best option is to run it on an ordinary Xojo thread. libssh2 doing most everything synchronously so running on the main thread of the main app (e.g. in Button.Action) will definitely cause the GUI to lock up a lot.
