### ISSUE TITLE
DLL locations?

### ISSUE THREAD

**Issue by rabeyer** [charonn0/RB-libssh2#5]
I have obtained the libssh2 and libcrypto-1_1 DLLs for Windows. I'm confused regarding where they should be located. Any suggestions? Thanks in advance.

**Comment by charonn0** [comment]
The DLLs should be in the same folder as the EXE file.

**Comment by rabeyer** [comment]
Thanks, that's what I thought...that isn't working for some reason...I'm getting the PlatformNotSupportedException error using part of your sample code for command execution:

Dim sh As SSH.Channel = SSH.OpenChannel("ssh://"+user+":"+password+"@"+IPAddress)
sh.DataMode = SSH.ExtendedDataMode.Merge ' redirect stderr to stdout
'Call sh.Execute("echo "+password+" | sudo -S shutdown -h now")
Call sh.Execute("echo "+password+" | sudo -S ps -al")
Dim result As String
Do Until sh.EOF
  Call sh.Poll()
  If sh.BytesReadable > 0 Then
    result = result + sh.Read(sh.BytesReadable, 0) ' 0 indicates StdOut/In
  End If
Loop
sh.Close

**Comment by charonn0** [comment]
Are you using 32-bit DLLs with a 64-bit app (or vice versa)?

**Comment by rabeyer** [comment]
I confirmed that I have 64-bit compiled app and 64-bit versions of the libraries:
libssh2-1.10.0_5-win64-mingw
__64-libcrypto-1_1-x64.dll1.1.1.0

**Comment by charonn0** [comment]
It looks like libssh2 got an update recently (1.10.0) and now links against a newer version of libcrypto. Try replacing `libcrypto-1_1-x64.dll` with `libcrypto-3-x64.dll` (available here: https://curl.se/windows/dl-7.78.0_5/openssl-3.0.0_5-win64-mingw.zip)

**Comment by rabeyer** [comment]
That solved it. Thanks so much!
